### ISSUE TITLE
CI/CD and Travis

### ISSUE THREAD

**Issue by davehodg** [LorenzoTa/step-by-step-tutorial-on-perl-module-creation-with-tests-and-git#3]
Possibly worth a mention. 

Even as a mostly solo dev I found gitlab CI looking over my shoulder useful.

Having been on contracts where changing perl versions might have been a showstopper, Travis has been helpful.

Something on actually uploading would be nice.

Otherwise, great stuff! I see a mini-O'Reilly in the offing :)

**Comment by LorenzoTa** [comment]
thanks for looking,
I really I'm not an expert in this and I want to stay as much as possible close to the bare minimum.

Perhaps you can be interested in this other one? https://github.com/LorenzoTa/Version-Control-for-Perl-Developers

for the moment is empty but I'm collecting contributors

**Comment by davehodg** [comment]
I think the final upload to CPAN is what I'd miss most. And break out the development into its own paper.

Certainly, it's the bit I've forgotten from my (sad) modules.

**Comment by LorenzoTa** [comment]
the CPAN upload is probably worth to be added. I will consider it.
what do you mean with

> And break out the development into its own paper.

to split up the document?

**Comment by davehodg** [comment]
Yes. I think good development hygeine (perlcritic! Travis!, CI!) could have a paper all of its own.

When you have a nice, clean lump of code, then upload to CPAN (which I've forgotten how to do).

**Comment by LorenzoTa** [comment]
upload to cpan is even too much simple ;) 
For a coincidence I was pointed today [here](https://www.reddit.com/r/perl/comments/aembaz/perl_module_development_from_the_ground_with_step/) where it is explained well
